### ISSUE TITLE
TC-A-022-Getting error during max amount (bad request)

### ISSUE THREAD

**Issue by pravinlavate** [tfathima2303/QA1#43]
Actual result: when we click on max amount button and click on withdraw button getting bad request .(txn is not happen-for eth)... now getting http exception for ETH and USDT.

**Comment by pravinlavate** [comment]
Getting Error during Eth max withdrawal .


![Image](https://github.com/tfathima2303/QA1/assets/118526312/fbb0d472-3e72-4097-880d-ea2c08f2f249)

Merchant ID: M0547965

**Comment by ruchitapaliwal** [comment]
Merchant ID: M9396721
Order ID: H322KQAK39
Action: Merchant Withdrawal
Transaction Amount (crypto): 0.0462424 BTC
Transaction Network: Bitcoin
Destination Wallet: tb1qhjt2p689c449u3t78pc0pmhtqrzmwx8lxf3v6m(Trust Wallet btc)
Status: Processing

Merchant ID: M9396721
Order ID: 48F1SM6Z3H
Action: Merchant Withdrawal
Transaction Amount (crypto): 0.031680 ETH
Transaction Network: Ethereum
Destination Wallet: 0x7f6b456ab57355f08dbfc5c2e885273650c96f67(Trust Wallet ETH)
Status: Processing
